name: Sync tutorial with dC workspace

on:
  push:
    branches:
      - main
    paths:
      - ./tutorials/[0-9]*.ipynb

jobs:
  get-tutorials:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@v34
        with:
          json: true
          files: |
            ./tutorials/[0-9]*.ipynb

      - name: Create matrixes
        id: create_matrix
        run: |
          echo "${{ steps.files.outputs.all_changed_files }}"
          echo "${{ steps.files.outputs.deleted_files }}"
